### PR TITLE
add data source alerting channel office365

### PR DESCRIPTION
**Pull request by rumenvasilev**
I would like to add this data source. Implementation-wise I've confirmed it works with terraform code and instana server. Documentation is added too.
Sadly I had to copy the implementation for AlertingChannels to AlertingChannelsDS, due to the fact the former is used as pointer receiver, while we need a value receiver for the read-only interface implementation currently in use for the other data sources.

### CODE REVIEW

**Comment by rumenvasilev** [comment]
I've prepared a better DRY version of the alert channel code, but will push it tomorrow after I validate it functions properly. If you don't insist on a DRY-er version for now, I'll keep it for a different PR.

**Comment by gessnerfl** [comment]
@rumenvasilev I would prefer a DRY-er version. I you don't feel comfortable I would be ok with the change, merge it into a feature branch and cross check options to clean up.

**Comment by rumenvasilev** [comment]
> @rumenvasilev I would prefer a DRY-er version. I you don't feel comfortable I would be ok with the change, merge it into a feature branch and cross check options to clean up.

Here's a more compact version. Tested, still works as before.
The only missing piece I couldn't find is if there's any limitation of characters and length of alert channel name. Instana API doesn't mention that in their docs, hence why I left the comment in the code.

**Review by gessnerfl — APPROVED** [review]

**Comment by gessnerfl** [comment]
@rumenvasilev thanks a lot for your contribution. I will take it from here and finalize the change on a feature branch

**Pull request merged**
